### PR TITLE
Rebranded and updated files with branding

### PR DESCRIPTION
**Pull request by derek-hwang27**
Did some rebranding and the such. Also added link to Malhar

### CODE REVIEW

**Review by michl1001 — COMMENTED** [review]
Should we add team branding stuff to the team page?

**Comment by derek-hwang27** [comment]
> Should we add team branding stuff to the team page?

**Comment by derek-hwang27** [comment]
not a bad idea, probably just a team name then

**Comment by derek-hwang27** [comment]
in fact there is a team name already there, so unless you are thinking about a picture or something, probably that is enough

**Comment by michl1001** [comment]
Aight, I posted details on slack

I just saw your comment on the team page and just wanted to make sure if the team page was fine. We do probably need to add some stuff to the branding folder though (canvas assignment is looking for brand stuff for the rest of our materials)

**Comment by derek-hwang27** [comment]
will probably draft up an icon or something tomorrow and push that into the repo

**Comment by michl1001** [comment]
Aight, the logo isn't that time-sensitive, but I say we should mention some kind of color scheme (I posted a good suggestion in manager chat)

**Comment by derek-hwang27** [comment]
added hex codes (may add more, but that's good imo for now)

**Review by michl1001 — APPROVED** [review]
Aight! Looks good then!

**Pull request merged**
